application:
  host: 0.0.0.0
database:
  host: "dpg-cdd80jg2i3mond6dvmfg-a.singapore-postgres.render.com"
  port: 5432
  username: "user"
  password: "bILGkTcNycWH4Y5j2DJ1sAFyTVos6KhM"
  database_name: "pharmacitydb"
