application:
  host: 0.0.0.0
database:
  host: "dpg-cee3v1ta4997f3l1gvs0-a.singapore-postgres.render.com"
  port: 5432
  username: "pharmacity_rust_user"
  password: "NGAibKzE0CkOzQ9G6rH1pf0jnKmt5N4X"
  database_name: "pharmacity_rust"
